site_name: Hello Package

nav:
  - Home: index.md
  - Calculator: calculator.md


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

theme: readthedocs
