site_name: Hello Package

nav:
  - Home: index.md
  - Addtion: add.md
  - API: API.md
  - SQL: SQL.md


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

theme: readthedocs
